#!/usr/bin/env bash
# Date: Coded on Jan 29, 2020.
echo "This shell script converts Farenheit (F) to Celsius (C)."
echo "Author: Alejandro Moliné."
echo
read -p "Enter the Farenheit degrees: " f
celsius=$( echo "scale=2; (($f-32)*5)/9 " | bc) 
echo "That equals $celsius C."
